import type { AidStation, GpxPoint, RaceSettings, TrackStats } from '../types/trail'
import frozenPoints from './frozen_points.json'

export const DEMO_SETTINGS: RaceSettings = {
  raceName: 'Ultra Terrestre 2027',
  startDate: '2027-05-06',
  startTime: '06:00',
  winnerTargetHours: 34.5, // 34h30
  cutoffTargetHours: 82.0, // 82h00
  defaultFirstStopMin: 3,
  defaultLastStopMin: 15,
  nightPenaltyPercent: 8,
  nightStartHour: 19,
  nightEndHour: 6,
}

export const DEMO_TRACK_STATS: TrackStats = {
  "totalDistance": 223.1,
  "totalDPlus": 12408,
  "totalDMinus": 12392,
  "minElevation": 17,
  "maxElevation": 3051,
  "pointsCount": 12127
}

export const DEMO_AID_STATIONS: AidStation[] = [
  {
    "id": "st-01",
    "order": 1,
    "name": "Stade de Basse Vallée (DÉPART)",
    "distanceKm": 0,
    "type": "DEPART",
    "stopTimeFirstMin": 0,
    "stopTimeLastMin": 0,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 28.4,
    "lat": -21.37403,
    "lon": 55.70751,
    "gpxPointIndex": 0
  },
  {
    "id": "st-02",
    "order": 2,
    "name": "Camphrier",
    "distanceKm": 10.59,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 12,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 714.9,
    "lat": -21.33927,
    "lon": 55.70613,
    "gpxPointIndex": 484
  },
  {
    "id": "st-03",
    "order": 3,
    "name": "Foc foc",
    "distanceKm": 25.33,
    "type": "COMPLET",
    "stopTimeFirstMin": 4,
    "stopTimeLastMin": 20,
    "accessibility": "ROUTE",
    "network": "ZONE_BLANCHE",
    "medical": true,
    "dormitory": false,
    "elevation": 2332.9,
    "lat": -21.23173,
    "lon": 55.67313,
    "gpxPointIndex": 1116
  },
  {
    "id": "st-04",
    "order": 4,
    "name": "Parking nez de boeuf",
    "distanceKm": 41.03,
    "type": "COMPLET",
    "stopTimeFirstMin": 3,
    "stopTimeLastMin": 25,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 2024.3,
    "lat": -21.20064,
    "lon": 55.62022,
    "gpxPointIndex": 2014
  },
  {
    "id": "st-05",
    "order": 5,
    "name": "Champ de foire",
    "distanceKm": 48.35,
    "type": "COMPLET",
    "stopTimeFirstMin": 4,
    "stopTimeLastMin": 15,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 1598.9,
    "lat": -21.1964,
    "lon": 55.57849,
    "gpxPointIndex": 2348
  },
  {
    "id": "st-06",
    "order": 6,
    "name": "Horloge",
    "distanceKm": 55.13,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 15,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 1369.7,
    "lat": -21.19073,
    "lon": 55.535,
    "gpxPointIndex": 2524
  },
  {
    "id": "st-07",
    "order": 7,
    "name": "Gd bassin",
    "distanceKm": 59.42,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 45,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 723.8,
    "lat": -21.1808,
    "lon": 55.53563,
    "gpxPointIndex": 2878
  },
  {
    "id": "st-08",
    "order": 8,
    "name": "Mare a boue",
    "distanceKm": 66.96,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 15,
    "accessibility": "PIETON",
    "network": "ZONE_BLANCHE",
    "medical": false,
    "dormitory": false,
    "elevation": 1603.4,
    "lat": -21.16046,
    "lon": 55.57073,
    "gpxPointIndex": 3194
  },
  {
    "id": "st-09",
    "order": 9,
    "name": "Parking marsoin",
    "distanceKm": 75.62,
    "type": "COMPLET",
    "stopTimeFirstMin": 5,
    "stopTimeLastMin": 30,
    "accessibility": "INTERDIT",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 1373.3,
    "lat": -21.1101,
    "lon": 55.56487,
    "gpxPointIndex": 3584
  },
  {
    "id": "st-10",
    "order": 10,
    "name": "Hell bourg",
    "distanceKm": 88.6,
    "type": "COMPLET",
    "stopTimeFirstMin": 3,
    "stopTimeLastMin": 20,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 1026.6,
    "lat": -21.07109,
    "lon": 55.52186,
    "gpxPointIndex": 4210
  },
  {
    "id": "st-11",
    "order": 11,
    "name": "Gite dufour 1",
    "distanceKm": 96.36,
    "type": "EAU",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 10,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 2488.6,
    "lat": -21.10948,
    "lon": 55.49558,
    "gpxPointIndex": 4727
  },
  {
    "id": "st-12",
    "order": 12,
    "name": "Sommet piton",
    "distanceKm": 99.45,
    "type": "EAU",
    "stopTimeFirstMin": 1,
    "stopTimeLastMin": 5,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 3050.4,
    "lat": -21.09915,
    "lon": 55.47999,
    "gpxPointIndex": 4920
  },
  {
    "id": "st-13",
    "order": 13,
    "name": "Gite dufour 2",
    "distanceKm": 102.54,
    "type": "EAU",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 10,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 2476,
    "lat": -21.10985,
    "lon": 55.49606,
    "gpxPointIndex": 5110
  },
  {
    "id": "st-14",
    "order": 14,
    "name": "Cilaos",
    "distanceKm": 112.19,
    "type": "BASE_VIE",
    "stopTimeFirstMin": 12,
    "stopTimeLastMin": 45,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 1213.9,
    "lat": -21.13566,
    "lon": 55.4755,
    "gpxPointIndex": 5731
  },
  {
    "id": "st-15",
    "order": 15,
    "name": "Pied taibit",
    "distanceKm": 119.44,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 15,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 1255.7,
    "lat": -21.11729,
    "lon": 55.4504,
    "gpxPointIndex": 6041
  },
  {
    "id": "st-16",
    "order": 16,
    "name": "Marla",
    "distanceKm": 125.69,
    "type": "COMPLET",
    "stopTimeFirstMin": 4,
    "stopTimeLastMin": 25,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 1618.1,
    "lat": -21.1041,
    "lon": 55.43335,
    "gpxPointIndex": 6579
  },
  {
    "id": "st-17",
    "order": 17,
    "name": "La nouvelle",
    "distanceKm": 132.46,
    "type": "COMPLET",
    "stopTimeFirstMin": 4,
    "stopTimeLastMin": 20,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": true,
    "dormitory": false,
    "elevation": 1440.1,
    "lat": -21.07631,
    "lon": 55.42468,
    "gpxPointIndex": 6960
  },
  {
    "id": "st-18",
    "order": 18,
    "name": "Roche plate",
    "distanceKm": 141.8,
    "type": "COMPLET",
    "stopTimeFirstMin": 3,
    "stopTimeLastMin": 18,
    "accessibility": "HELICO",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 1171.6,
    "lat": -21.06992,
    "lon": 55.40603,
    "gpxPointIndex": 7668
  },
  {
    "id": "st-19",
    "order": 19,
    "name": "Maido",
    "distanceKm": 149.31,
    "type": "COMPLET",
    "stopTimeFirstMin": 0,
    "stopTimeLastMin": 25,
    "accessibility": "PIETON",
    "network": "ZONE_BLANCHE",
    "medical": true,
    "dormitory": true,
    "elevation": 2168.3,
    "lat": -21.06966,
    "lon": 55.38763,
    "gpxPointIndex": 8246
  },
  {
    "id": "st-20",
    "order": 20,
    "name": "Tamarin",
    "distanceKm": 164.24,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 5,
    "accessibility": "PIETON",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 1827.6,
    "lat": -21.10642,
    "lon": 55.36466,
    "gpxPointIndex": 9161
  },
  {
    "id": "st-21",
    "order": 21,
    "name": "Piton oranger",
    "distanceKm": 174.46,
    "type": "COMPLET",
    "stopTimeFirstMin": 2,
    "stopTimeLastMin": 15,
    "accessibility": "PIETON",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 1894.8,
    "lat": -21.04986,
    "lon": 55.37775,
    "gpxPointIndex": 9647
  },
  {
    "id": "st-22",
    "order": 22,
    "name": "Halte la",
    "distanceKm": 192.1,
    "type": "BASE_VIE",
    "stopTimeFirstMin": 10,
    "stopTimeLastMin": 55,
    "accessibility": "PIETON",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 215.6,
    "lat": -20.96773,
    "lon": 55.33396,
    "gpxPointIndex": 10535
  },
  {
    "id": "st-23",
    "order": 23,
    "name": "Cap noir",
    "distanceKm": 200.37,
    "type": "COMPLET",
    "stopTimeFirstMin": 3,
    "stopTimeLastMin": 10,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 1140.3,
    "lat": -20.98855,
    "lon": 55.38756,
    "gpxPointIndex": 10920
  },
  {
    "id": "st-24",
    "order": 24,
    "name": "Colorado",
    "distanceKm": 216.1,
    "type": "COMPLET",
    "stopTimeFirstMin": 3,
    "stopTimeLastMin": 15,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": true,
    "dormitory": true,
    "elevation": 659.6,
    "lat": -20.90615,
    "lon": 55.42505,
    "gpxPointIndex": 11726
  },
  {
    "id": "st-25",
    "order": 25,
    "name": "La Redoute - Saint-Denis (ARRIVÉE)",
    "distanceKm": 223.1,
    "type": "COMPLET",
    "stopTimeFirstMin": 0,
    "stopTimeLastMin": 0,
    "accessibility": "ROUTE",
    "network": "GSM",
    "medical": false,
    "dormitory": false,
    "elevation": 45.8,
    "lat": -20.88498,
    "lon": 55.44212,
    "gpxPointIndex": 12126
  }
]

export function generateDemoGpxTrack(): { points: GpxPoint[]; stats: TrackStats } {
  return {
    points: frozenPoints as GpxPoint[],
    stats: DEMO_TRACK_STATS,
  }
}
